### ISSUE TITLE
Extend Documentation

### ISSUE THREAD

**Issue by maxim-tschumak** [maxim-tschumak/enterprise-computing-ws16#11]

**Comment by maxim-tschumak** [comment]
@xrxtal @rigvedpatki @JonathanHeiss we should all do this ;)

**Comment by theanhly** [comment]
don't worry. i am on it.

**Comment by maxim-tschumak** [comment]
me too :)

**Comment by Jordex** [comment]
Maybe we should split up the tasks to simplify collaboration. Like on the one hand Performance, scalability, fault tolerance, security can be treated as seperated sections and on the other hand each technical and process challange. I will put the headlines into the Doc. since this is a proposal please let me know if you disagree ;)

**Comment by Jordex** [comment]
I will start with Fault tolerance and performance^^
